# Generated by Django 3.2.8 on 2021-10-10 23:46

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_search_vector_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quote',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='quotes_quot_search__829c7d_gin'),
        ),
    ]
